apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/operator-type: non-standalone
  name: openstack-baremetal-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OpenStackBaremetalSet is the Schema for the openstackbaremetalsets
        API
      displayName: OpenStack BaremetalSet
      kind: OpenStackBaremetalSet
      name: openstackbaremetalsets.baremetal.openstack.org
      version: v1beta1
    - description: OpenStackProvisionServer used to serve custom images for baremetal
        provisioning with Metal3
      displayName: OpenStackProvisionServer
      kind: OpenStackProvisionServer
      name: openstackprovisionservers.baremetal.openstack.org
      version: v1beta1
  description: An operator for handling baremetal provisioning concerns for OpenStack
  displayName: OpenStack Baremetal Operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cn-openstack
  - openstack
  links:
  - name: Openstack Baremetal Operator
    url: https://github.com/openstack-k8s-operators/openstack-baremetal-operator
  maturity: beta
  provider:
    name: Red Hat
    url: https://redhat.com/
  version: 0.0.0
